# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='happy',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='happy_images'),
        ),
    ]
